FROM golang:latest AS builder

WORKDIR /app

COPY ./app/* /app/

RUN ["go", "build", "."]

CMD [ "./hello-world" ]

FROM scratch AS prod
WORKDIR /app
COPY --from=builder /app/hello-world .

CMD [ "./hello-world" ]
